services:
  db:
    image: postgres:15-alpine
    container_name: exam_mate_db
    restart: always
    environment:
      POSTGRES_DB: exam_mate_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - exam_mate_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        - BUILDKIT_INLINE_CACHE=0
    container_name: exam_mate_backend
    restart: always
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/prisma/generated
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/exam_mate_db?schema=public
      PORT: 5000
    networks:
      - exam_mate_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        - BUILDKIT_INLINE_CACHE=0
    container_name: exam_mate_frontend
    restart: always
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_DISABLE_NATIVE_MODULES=true
      - ROLLUP_SKIP_LOAD_NATIVE_PLUGIN=true
      - NODE_OPTIONS=--max-old-space-size=2048
    depends_on:
      - backend
    networks:
      - exam_mate_network

volumes:
  postgres_data:
  frontend_node_modules:

networks:
  exam_mate_network:
    driver: bridge 