FROM node:18-alpine

WORKDIR /app

# Sadece bağımlılıklar için gerekli dosyaları kopyala
COPY package*.json ./
COPY prisma ./prisma/

# Bağımlılıkları yükle ve önbelleğe al
RUN npm ci --only=production && \
    npx prisma generate && \
    npm cache clean --force

# Geliştirme bağımlılıklarını ayrıca yükle
RUN npm install --only=development

# Tüm dosyaları kopyala
COPY . .

# Uygulamayı çalıştır - migrasyon ve seed işlemlerini ekle
CMD ["sh", "-c", "npx prisma migrate deploy && npx prisma db seed && npm run start:dev"] 